### ISSUE TITLE
Attune methods not accepting bluesky formatted wt5 files

### ISSUE THREAD

**Issue by kameyer226** [wright-group/attune#159]
Multidimensional axis errors when attempting to use `attune.intensity` with files created using bluesky.   Returns errors:

_MultidimensionalAxisError: (MultidimensionalAxisError(...), 'moment can not handle multidimensional axis: 1')_

due to new Axes being N-D (N>1) rather than 1D

**Comment by ksunden** [comment]
transform to the points arrays, this has little to do with bluesky

The same transforms apply with older code, though some names are a bit more explicit in bluesky than they were (e.g. channel names carry prefix)
