### ISSUE TITLE
Generic functions: workup.setpoint and workup.intensity

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/attune#17]
We should have two methods which take a data object and setpoints. The methods return offsets (optionally splined with some way [**kwargs] to tweak the spline). These methods **do not** interact with curve objects or make figures. 
- `workup._intensity` (2D data)
- `workup._setpoint` (3D data)
Note, `workup.tune_test` and `workup.sdc` will call `workup._intensity`.

We should have two methods which take data and curves objects and runs through the flow specified in #16. These methods take positional arguments of data object, curve object, and channel (defaults to 0); kwargs include save, save\_directory, level, first round cleaning cutoff factors: gtol and ltol, spline **kwargs,  
- `workup.setpoint`
- `workup.intensity`
These methods will return figures like the below photo.
![image](https://user-images.githubusercontent.com/15792657/51872193-2ba90900-231e-11e9-9d10-a27bb7ac31eb.png)

**Comment by ksunden** [comment]
Tune test is actually different, it and intensity are done

**Comment by ksunden** [comment]
These methods are done, if there is any further changes, a new issue may be opened
