### ISSUE TITLE
Have workup methods accept curve=None and then intuit setpoints from data object

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/attune#19]

**Comment by ksunden** [comment]
Currently for `intensity` (and probably will be for `setpoint`), curve is optional, but if not given, it gives a single axis differential curve as a result (e.g. coset)

I do think having a curve constructor that looks at a data object would be good to have.... That information is there for the taking. (Though some thought may need to go into typing and "topology" e.g. curves/subcurves)

At this time, I think this should be a separate function, that does not have to do with workup directly

**Comment by ksunden** [comment]
This is done, where it makes sense to not have curves input, AFAIK.

If there are more specific instances where this could be true but is not, please reopen/open a targetted issue
