### ISSUE TITLE
curve level

### ISSUE THREAD

**Issue by untzag** [wright-group/attune#2]
with the addition of poynting curves, there are now curves that should logically be tied together

they are only different objects because of the 'one object, one file' heuristic

we should consider giving curves more knowledge about their relationship

one idea is to endow curves with a `level` integer---curves with the same level would require each-other to have the same points

another idea is to create some kind of super curve container that handles all of our current objects

**Comment by ksunden** [comment]
We have had discussions about the idea of having "sibling" curves in addition to "sub/child" curves
