### ISSUE TITLE
method to add dependent(s) to curve

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/attune#29]

**Comment by ksunden** [comment]
Perhaps `__setitem__` ?

Currently this can be accomplished relatively easily 

```
curve.dependents["new"] = Dependent([1,2,3], "name", "units")
curve.interpolate()
```

May need to add `setattr(curve, "new", curve.dependents["new"])` to finish off.

These can all be implemented in `__setitem__`, Though internally we may still avoid using it when we are operating on many Dependents at once, so as to avoid reinterpolating more than needed

**Comment by ksunden** [comment]
We may also want `__delitem__` to remove dependents.
