### ISSUE TITLE
Make code header more representative of actual code purpose.

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/attune#67]
https://github.com/wright-group/attune/blob/3e2841243216c4fbd34c794afa77104ff602488c/attune/workup/_intensity.py#L1

https://github.com/wright-group/attune/blob/3e2841243216c4fbd34c794afa77104ff602488c/attune/workup/__init__.py#L1

https://github.com/wright-group/attune/blob/3e2841243216c4fbd34c794afa77104ff602488c/attune/workup/_setpoint.py#L1

https://github.com/wright-group/attune/blob/3e2841243216c4fbd34c794afa77104ff602488c/attune/workup/_tune_test.py#L1

**Comment by ksunden** [comment]
These have been remedied at some point, not sure when...
