### ISSUE TITLE
ltol potentially not functioning correctly in workup.intensity

### ISSUE THREAD

**Issue by jscheeler1** [wright-group/attune#85]
Last week when working up SDC, ltol was varied but it didn't do anything to the fitting. When playing more with it a couple minutes ago, ltol seemed to be responsive. Maybe just double check that it's working as we intend?

**Comment by darienmorrow** [comment]
@jscheeler1 consider uploading the offending dataset and figure...

**Comment by jscheeler1** [comment]
The dataset can be found at C:\Users\John\Drive\MX2\CMDS\2020-01-14\SDC\009 SCAN [w1, d2]\000.data. The first figure below has ltol=0.01, gtol=0.001. The second figure below has ltol=0.1, gtol=0.01. The grey fit changes between pictures, so it looks to me like ltol could be behaving properly.

![ltol=0 01 gtol=0 001](https://user-images.githubusercontent.com/45218489/72923480-c7dcd480-3d14-11ea-91b1-6a08fee3e0b6.png)
![ltol=0 1, gtol=0 01](https://user-images.githubusercontent.com/45218489/72923488-cca18880-3d14-11ea-86d5-d6282d3375fe.png)

**Comment by ksunden** [comment]
The data file itself would be useful... Current master fixes the bug re: gray line being flipped, so will make the comparison more useful

By my first reaction, this is behaving largely as I expect, don't see an obvious sign that it is incorrect... It is hard to tell, however, since both ltol and gtol are changing in this example

**Comment by darienmorrow** [comment]
Shouldn't clipped values be gray?

**Comment by ksunden** [comment]
@darienmorrow Currently clipped values are in a gray _colormap_, I believe, so it's hard to tell for low values, but if you bump up `ltol` to ~0.5, it becomes quite obvious

**Comment by DLafayetteII** [comment]
It is possible that ltol argument does nothing in pycmds tune intensity acquisition module, despite functioning in manual use of attune.workup.intensity. I mention this now as I believe this is the case for attune.workup.tune_test, raising an separate issue momentarily.

**Comment by kameyer226** [comment]
Can you get reasonable results if you only adjust `gtol` and ignore `ltol` by setting it to zero?   Offset location is currently found using center of mass which is susceptible to noise and changes in noise as when `ltol` is adjusted.  Probably the reason for the spikes at 7000 and 8100 where the intensity drops.
