### ISSUE TITLE
attune.workup.intensity writes setpoints in reverse order

### ISSUE THREAD

**Issue by DLafayetteII** [wright-group/attune#88]
My workup script, data, base curve, old mixer curve, and output mixer curve can be found at [https://drive.google.com/drive/folders/1NkttlKdqvXdg-ba5to3vs27vfgJZFd0Y]. I have used the script since, so, at a minimum, the file location and curve names will need to be updated for use. The order of the base motor setpoints for Non-Non-SH-Idl is reversed from the old curve to the new curve. The motor positions are optimal for light production if I manually reorder the base Idl wavelengths. I do not have this specific issue if I allow pycmds to auto-process the tune_intensity workup. The reversal is reproducible with this script and new curve inputs. The desired output is for the new SH-Idl Mixer 1 curve to maintain the Idler setpoints, in proper order, of the old curve.

**Comment by ksunden** [comment]
I'm going to close for now, I think this is fixed, but if it comes up again, feel free to reopen (intensity has been rewritten since this was raised)
